mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  database:
    url: jdbc:mysql://127.0.0.1:3306/test1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

